from django.db import models

class DadosImportados(models.Model):
    ref_giant = models.CharField(max_length=255, primary_key=True, verbose_name="Referência Giant")  
    mawb = models.CharField(max_length=255, blank=True, null=True, verbose_name="MAWB")
    hawb = models.CharField(max_length=255, blank=True, null=True, verbose_name="HAWB")
    q = models.CharField(max_length=255, blank=True, null=True, verbose_name="Q")
    c3 = models.CharField(max_length=255, blank=True, null=True, verbose_name="C3")
    deliveryid = models.CharField(max_length=255, blank=True, null=True, verbose_name="Delivery ID")
    sostatus_releasedonholdreturned = models.CharField(max_length=255, blank=True, null=True, verbose_name="Status RELEASED / ON HOLD / RETURNED")
    data_liberacao = models.DateField(blank=True, null=True, verbose_name="Data Liberação")  
    cipbrl = models.CharField(max_length=255, blank=True, null=True, verbose_name="CIPBRL")
    pc = models.CharField(max_length=255, blank=True, null=True, verbose_name="PC")
    peso = models.DecimalField(max_digits=12, decimal_places=2, blank=True, null=True, verbose_name="Peso")  
    peso_cobravel = models.DecimalField(max_digits=12, decimal_places=2, blank=True, null=True, verbose_name="Peso Cobrável")  
    tipo = models.CharField(max_length=255, blank=True, null=True, verbose_name="Tipo")  
    pupdt = models.DateField(blank=True, null=True, verbose_name="Data PUPDT")
    ciok = models.DateField(blank=True, null=True, verbose_name="Data CIOK")
    lientrydt = models.DateField(blank=True, null=True, verbose_name="Data LI Entry")
    liok = models.DateField(blank=True, null=True, verbose_name="Data LI OK")
    ok_to_ship = models.CharField(max_length=255, blank=True, null=True, verbose_name="OK to Ship")  
    li = models.CharField(max_length=255, blank=True, null=True, verbose_name="LI")
    hawbdt = models.DateField(blank=True, null=True, verbose_name="Data HAWB")
    estimatedbookingdt = models.DateField(blank=True, null=True, verbose_name="Data Estimada Booking")
    arrivaldestinationdt = models.DateField(blank=True, null=True, verbose_name="Data Chegada Destino")
    solicitacao_fundos = models.CharField(max_length=255, blank=True, null=True, verbose_name="Solicitação de Fundos")  
    fundos_recebidos = models.CharField(max_length=255, blank=True, null=True, verbose_name="Fundos Recebidos")  
    eadidt = models.DateField(blank=True, null=True, verbose_name="Data EAD")
    diduedt = models.DateField(blank=True, null=True, verbose_name="Data DI Due")
    diduenumber = models.CharField(max_length=255, blank=True, null=True, verbose_name="Número DU")  
    icmspago = models.DateField(max_length=255, blank=True, null=True, verbose_name="ICMS Pago")  
    canal_cor = models.CharField(max_length=255, blank=True, null=True, verbose_name="Canal Cor")  
    data_liberacao_ccr = models.DateField(blank=True, null=True, verbose_name="Data Liberação CCR")  
    data_nfe = models.DateField(blank=True, null=True, verbose_name="Data NFE")  
    numero_nfe = models.CharField(max_length=255, blank=True, null=True, verbose_name="Número NFE")  
    nftgdt = models.CharField(max_length=255, blank=True, null=True, verbose_name="NFTGDT")
    nftg = models.CharField(max_length=255, blank=True, null=True, verbose_name="NFTG")
    dlvatdestination = models.DateField(blank=True, null=True, verbose_name="Data Chegada Destino")  
    status_impexp = models.CharField(max_length=255, blank=True, null=True, verbose_name="Status Import/Export")  
    data_estimada = models.DateField(blank=True, null=True, verbose_name="Data Estimada")  
    eventos = models.TextField(blank=True, null=True, verbose_name="Eventos")  
    real_lead_time = models.CharField(max_length=255, blank=True, null=True, verbose_name="Real Lead Time")
    ship_failure_days = models.CharField(max_length=255, blank=True, null=True, verbose_name="Ship Failure Days")
    tipo_justificativa_atraso = models.CharField(max_length=255, blank=True, null=True, verbose_name="Tipo Justificativa Atraso")  
    justificativa_atraso = models.CharField(max_length=500, blank=True, null=True, verbose_name="Justificativa Atraso")  

    class Meta:
        db_table = 'dados_importados'

    def __str__(self):
        return self.ref_giant
